FROM python
RUN mkdir work ./work/shared ./work/source
WORKDIR ./work
COPY requirements.txt shell.sh pyscript.py start.sh start1.sh  ./ 
RUN apt-get update
RUN apt-get -y  install python3-pip inotify-tools
RUN pip install -r requirements.txt
CMD ["bash","shell.sh","&"]



